version: '3.8'
services:
  # database:
  #   container_name: tourlibras-db
  #   image: 'postgres:16'
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  #   volumes:
  #     - tourlibras_data:/var/lib/postgresql/data
  api:
    container_name: tourlibras-api
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - '80:${APP_PORT}'
    # depends_on:
    #   - database
volumes:
  tourlibras_data:
