version: '3.8'
services:
  api:
    container_name: tourlibras-api
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - '80:${APP_PORT}'
volumes:
  tourlibras_data:
