version: '3.9'
services:
  db:
    container_name: tourlibras-db
    image: 'postgres:15.4'
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    container_name: tourlibras-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '80:${APP_PORT}'
      - '443:${APP_PORT}'
    depends_on:
      - db
volumes:
  db_data:
